"""create users table

Revision ID: 13a61e39d2f6
Revises: 
Create Date: 2024-11-30 17:07:47.294638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a61e39d2f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the farmers table
    op.create_table(
        'farmers',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('ndoc', sa.String, unique=True, nullable=False),
    )
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    # Drop the farmers table
    op.drop_table('farmers')
    # ### end Alembic commands ###
